### Hello functions
POST {{parastats_tasks_base_url}}
Content-Type: application/json

{
  "name": "HelloWorld",
  "hello": "World"
}




### FetchAllActivities
POST {{parastats_tasks_base_url}}
Content-Type: application/json

{
  "name": "FetchAllActivities",
  "pilotId": 4142500
}

### SyncSites
POST {{parastats_tasks_base_url}}
Content-Type: application/json

{
  "name": "SyncSites"
}

### WingActivity
POST {{parastats_tasks_base_url}}
Content-Type: application/json

{
  "name": "WingActivity",
  "flightId": 14659467895
}