version: "3"

tasks:
  build:
    desc: Build the functions
    dir: functions
    sources:
      - src/**/*.ts
      - exclude: src/**/*.test.ts
    generates:
      - ./dist/
    cmds:
      - rm -rf ./dist/*
      - yarn buildProd
      - cp package.prod.json dist/package.json

  webhooks:logs:
    desc: View webhooks logs
    cmds:
      - open https://console.cloud.google.com/run/detail/us-east1/parastats-webhooks/logs?authuser=1&project=para-stats

  tasks:logs:
    desc: View tasks logs
    cmds:
      - open https://console.cloud.google.com/run/detail/us-east1/parastats-tasks/logs?authuser=1&project=para-stats

  tasks:tail:
    desc: Tail tasks logs in terminal
    cmds:
      - gcloud logging tail "resource.type=cloud_run_revision AND resource.labels.service_name=parastats-tasks" --project=para-stats