version: "3"

dotenv: [ 'functions/.env' ]

includes:
  infra: ./infra
  functions: ./functions
  db: ./database

tasks:
  deploy:
    desc: Deploy
    cmds:
      - task: functions:build
      - task: infra:apply