version: "3"

dotenv: [ 'functions/.env' ]

includes:
  infra: ./infra
  functions: ./functions
  site: ./site

tasks:
  deploy:
    desc: Deploy
    cmds:
      - task: functions:build
      - task: site:deploy
      - task: infra:apply


  local-build:
    desc: Compose Build
    cmds:
      - docker compose  --env-file .env -f compose.yaml build