version: "3"

dotenv: [ 'webhooks/.env' ]

includes:
  infra: ./infra
  webhooks: ./webhooks
  db: ./database

tasks:
  deploy:
    desc: Deploy
    cmds:
      - task: webhooks:build
      - task: infra:apply