version: "3"

tasks:

  build:
    desc: Build the image
    internal: true
    cmds:
      - |
        docker build -f site/prod.Dockerfile \
        -t europe-west1-docker.pkg.dev/para-stats/parastats/parastats-site:{{.TAG}} \
        --platform linux/amd64 \
        --build-arg DATABASE_HOST={{.DATABASE_HOST}} \
        --build-arg DATABASE_NAME={{.DATABASE_NAME}} \
        --build-arg DATABASE_PASSWORD={{.DATABASE_PASSWORD}} \
        --build-arg DATABASE_PORT={{.DATABASE_PORT}} \
        --build-arg NEXT_PUBLIC_MAPBOX_TOKEN={{.NEXT_PUBLIC_MAPBOX_TOKEN}} \
        --build-arg DATABASE_USER={{.DATABASE_USER}} \
        .

  push:
    desc: Push the image
    internal: true
    dir: site
    requires:
      vars: [ TAG ]
    cmds:
      - docker push europe-west1-docker.pkg.dev/para-stats/parastats/parastats-site:{{.TAG}}

  update-version:
    desc: Update versions in file
    internal: true
    dir: site
    requires:
      vars: [ TAG ]
    cmds:
      - sed -i '' 's/^site_tag = .*/site_tag = "{{.TAG}}"/' ../infra/terraform.tfvars

  deploy:
    desc: Deploy site image
    vars:
      TAG: '{{now | unixEpoch}}'
    cmds:
      - task: build
        vars:
          TAG:
            ref: .TAG
      - task: push
        vars:
          TAG:
            ref: .TAG
      - task: update-version
        vars:
          TAG:
            ref: .TAG
