### Hello functions
GET https://tasks.parastats.info
Content-Type: application/json


### FetchAllActivities
POST localhost:3000
Content-Type: application/json

{
  "name": "FetchAllActivities",
  "userId": 4142500
}

### WingActivity
POST localhost:3000
Content-Type: application/json

{
  "name": "WingActivity",
  "activityId": 14443993504
}