### Hello functions
GET http://localhost:3000
Content-Type: application/json


### FetchAllActivities
GET localhost:8008
Content-Type: application/json

{
  "name": "FetchAllActivities",
  "userId": 4142500
}

### WingActivity
GET localhost:8008
Content-Type: application/json

{
  "name": "WingActivity",
  "activityId": 14432764863
}