version: "3"

tasks:
  build:
    desc: Build the webhooks
    dir: webhooks
    sources:
      - src/**/*.ts
      - exclude: src/**/*.test.ts
    generates:
      - ../dist/webhooks/
    cmds:
      - rm -r ../dist/webhooks/*
      - npm run build
      - cp package.prod.json ../dist/webhooks/package.json

  view-logs:
    desc: View log
    cmds:
      - open https://console.cloud.google.com/run/detail/us-east1/parastats-webhooks/logs?authuser=1&project=para-stats