version: "3"

tasks:
  build:
    desc: Build the webhooks
    dir: webhooks
    sources:
      - src/**/*.ts
    generates:
      - ../dist/webhooks/index.js
    cmds:
      - npm run build

  view-logs:
    desc: View log
    cmds:
      - open https://console.cloud.google.com/run/detail/us-east1/parastats-webhooks/logs?authuser=1&project=para-stats